version: "3.8"

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file:
      - ./backend/.env
    networks:
      - apinet

networks:
  apinet:
